image:
    - Visual Studio 2017
environment:
    BOOST_ROOT: C:\Libraries\boost_1_67_0
    AF_PATH: C:\Program Files\ArrayFire\v3
    matrix:
        - GENERATOR: "Visual Studio 15 Win64"
platform:
    - x64
cache:
    - c:\tools\vcpkg\installed\

clone_folder: C:\test-appveyor

before_build:
    - vcpkg install --triplet x64-windows gtest eigen3
    - appveyor DownloadFile "https://www.dropbox.com/s/ndt1eaouriiu4qi/ArrayFire-v3.5.1.zip?dl=1" -FileName ArrayFire-v3.5.1.zip
    - 7z x ArrayFire-v3.5.1.zip -o"C:\Program Files"
    - reg add HKCU\Software\Kitware\CMake\Packages\ArrayFire /v ArrayFire_CMake_DIR /d "C:\Program Files\ArrayFire\v3\cmake" /f
    - reg add "HKCU\Environment" /v PATH /d "C:\Program Files\ArrayFire\v3\lib" /f
build_script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G"%GENERATOR%"
    - cmake --build . --config Release
test_script:
    - ctest -C Release -V --output-on-failure