image:
    - Visual Studio 2017
environment:
    BOOST_ROOT: C:\Libraries\boost_1_67_0
    matrix:
        - GENERATOR: "Visual Studio 15 Win64"
platform:
    - x64
cache:
    - c:\tools\vcpkg\installed\

clone_folder: C:\test-appveyor

before_build:
    - vcpkg install --triplet x64-windows gtest eigen3
build_script:
    - mkdir build && cd build
    - cmake .. -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -G"%GENERATOR%"
    - cmake --build . --config Release
test_script:
    - ctest -C Release --output-on-failure